services:
  - type: web
    name: shoestore-frontend
    env: static
    buildCommand: ./build.sh
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://shoestorereactv2.onrender.com